### ISSUE TITLE
pypy wheels?

### ISSUE THREAD

**Issue by fschulze** [hynek/argon2-cffi#27]
Would it be possible to get pypy wheels on PyPI? It looks like you already have pypy running on Travis and Appveyor. I don't know whether you also use them for releases.

We currently can't easily run pypy tests for devpi on Travis and Appveyor, because this library would need to be compiled and it doesn't seem to be straight forward to do so. With wheels for pypy it would be much easier for us and installation of devpi with pypy would be a lot easier for other people as well.

**Comment by hynek** [comment]
My understanding is that PyPy has no stable ABI and

**Comment by hynek** [comment]
My understanding is that PyPy has no stable ABI and binary wheels are impossible?

C.f. also https://pypi.python.org/pypi/cryptography/1.8.1

cc @dstufft & @reaperhulk for confirmation

**Comment by reaperhulk** [comment]
Binary wheels aren't impossible but you need a different wheel for every pypy release (e.g. pypy2 5.8 is pp258), which makes them operationally impractical.

**Comment by hynek** [comment]
Oh OK.  Wasn’t there a time when they didn’t even tag the releases?  I seem to remember it might have even be me who opened a bug somewhere. :)

**Comment by reaperhulk** [comment]
I believe the current wheel tags aren't really from the pypy project, but rather the way the `pep425tags` module (which has a shared history but divergent codebase between pip/wheel) chose to handle it. dstufft probably knows more though.

**Comment by fschulze** [comment]
Then I must have totally misunderstood the purpose of ``cffi``. I thought the wheel would just contain the python stuff and a pre-compiled ``libargon2`` and ``cffi`` would do the rest.

**Comment by dstufft** [comment]
And yea, I think PyPy has a stable ABI now and we'll use it, but we need to implement the ``>=`` behavior that we implemented for CPython's stable ABI.

**Comment by reaperhulk** [comment]
@dstufft is there an issue open on pypa/pip for that? If we can nail down the parameters I'd be willing to do a PR updating `pep425tags` to handle it.

**Comment by dstufft** [comment]
Not that I recall, but afaik the current situation is that we produce tags like ``pp254-pypy_41-win32``, (interpreter, ABI, platform) so the ABI portion is correct, but the interpreter is still locking it to a specific version of PyPy. On CPython what we did was have it generate all previous versions of the ``cpXY`` tags in the huge list.

This is a bit more complicated for PyPy because (A) I'm not sure what the best way to detect a stable ABI is there, maybe just saying if it returns something that's the ABI and (B) they have a lot more versions to generate so the list can get quite large, we might want to invent a short hand like ``pp2`` and ``pp3`` to indicate PyPy Python v2.x and pp3 for PyPy Python v3.x-- but that would require a distutils-sig post.

**Comment by fschulze** [comment]
I just learned that one can use newer pypy(3) versions on Travis. With those it works out of the box. 

The naming seems to come from [pyenv](https://github.com/pyenv/pyenv/tree/master/plugins/python-build/share/python-build). The newest ones I was able to get working are these:
```
  - "pypy-5.4.1"
  - "pypy3.3-5.2-alpha1"
```

**Comment by stonebig** [comment]
Does it work with pypy3.7-v7.3.4-win64 ?

**Comment by hynek** [comment]
This is fixed by the outsourcing to https://github.com/hynek/argon2-cffi-bindings

We currently carry wheels for pypy3.7 and pypy3.8.

Feel free to try to pip-install argon2-cffi-bindings and report back if it's still broken.
